-- FACILITY TABLE
insert into location(loc_name) value('Briggs Field');
insert into location(loc_name) value('Ceurvels Field');
insert into location(loc_name) value('Calvin J. Ellis Field');
insert into location(loc_name) value('Forge Pond Park');
insert into location(loc_name) value('Amos Gallant Field');
insert into location(loc_name) value('B. Everett Hall');

-- FIELDS TABLE
insert into fields(fld_loc_id, fld_name) value(1, 'T-Ball');
insert into fields(fld_loc_id, fld_name) value(1, 'Other');
insert into fields(fld_loc_id, fld_name) value(2, 'Full-size Baseball');
insert into fields(fld_loc_id, fld_name) value(2, 'Little League');
insert into fields(fld_loc_id, fld_name) value(2, 'Softball');
insert into fields(fld_loc_id, fld_name) value(2, 'Lacrosse');
insert into fields(fld_loc_id, fld_name) value(2, 'Soccer');
insert into fields(fld_loc_id, fld_name) value(2, 'Basketball');
insert into fields(fld_loc_id, fld_name) value(2, 'Other');
insert into fields(fld_loc_id, fld_name) value(3, 'Little League #1');
insert into fields(fld_loc_id, fld_name) value(3, 'Little League #2');
insert into fields(fld_loc_id, fld_name) value(3, 'Little League #3');
insert into fields(fld_loc_id, fld_name) value(3, 'Field #4');
insert into fields(fld_loc_id, fld_name) value(3, 'Soccer');
insert into fields(fld_loc_id, fld_name) value(3, 'Other');
insert into fields(fld_loc_id, fld_name) value(4, 'Little League #1');
insert into fields(fld_loc_id, fld_name) value(4, 'Little League #2');
insert into fields(fld_loc_id, fld_name) value(4, 'Little League #3');
insert into fields(fld_loc_id, fld_name) value(4, 'Softball #4');
insert into fields(fld_loc_id, fld_name) value(4, 'Softball #5');
insert into fields(fld_loc_id, fld_name) value(4, 'Softball #6');
insert into fields(fld_loc_id, fld_name) value(4, 'Multi-Use Soccer');
insert into fields(fld_loc_id, fld_name) value(4, 'Multi-Use Lacrosse');
insert into fields(fld_loc_id, fld_name) value(4, 'Multi-Use Other');
insert into fields(fld_loc_id, fld_name) value(4, 'Pavilion');
insert into fields(fld_loc_id, fld_name) value(4, 'Kitchen & Pavilion');
insert into fields(fld_loc_id, fld_name) value(4, 'Other');
insert into fields(fld_loc_id, fld_name) value(5, 'Other');
insert into fields(fld_loc_id, fld_name) value(6, 'Full-Size Basketball');
insert into fields(fld_loc_id, fld_name) value(6, 'Little League [Front Field Only]');
insert into fields(fld_loc_id, fld_name) value(6, 'Basketball 1');
insert into fields(fld_loc_id, fld_name) value(6, 'Basket Ball 2');
insert into fields(fld_loc_id, fld_name) value(6, 'Football');
insert into fields(fld_loc_id, fld_name) value(6, 'Street Hockey Rink');
insert into fields(fld_loc_id, fld_name) value(6, 'Other');